### ISSUE TITLE
Overview of collaborators for possible partnerships

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#102]
Jess will build a google doc for possible partnerships & status

**Comment by jessicazartler** [comment]
Here is the basic working doc - feel free to fancy the template and design :) 

https://docs.google.com/spreadsheets/d/1N6nU97E2hPWQaHvNpSoTy_NuB_1lL6vuSTUlcQtTHNo/edit#gid=0

*On private - request editing access (because it has folks contacts) but let me know if you want me to change to link sharing view or anything :) Thank you!

Also, with this project, I think it would be great to hit up all the crypto facebook pages with a post of our efforts/campaign to reach out for contacts/funds - we should work on a social media pitch post together along with our elevator pitch :)

And, we should hit up all our friends and partners that are on the website and inform them of the campaign and see if they have some contacts/ideas for us

**Comment by krrisis** [comment]
doc created - see funding strategy for overview - thx again Jessica!
