### ISSUE TITLE
Host our own Jitsi Service

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/Communication#119]
@geleeroyale would you have interest in setting this up? :-D

**Comment by geleeroyale** [comment]
So, I had a look at the Jitsi architecture again. While it seems like there was considerable progress made, the process to run Jibri (the streaming component) on top of our own Jitsi Meet (the actual video-conferencing) is still very complicated. Furthermore this would need its own digitalocean droplet. So - in short - it is not undoable, but labor intensive and comes with a monthly cost.

There do not seem to be any competitors to Jitsi too.

**Proposed Solution:**
Since our problem is most likely temporary - I think we should reinforce the fallback method. I suggest opening a dropbox account that is dedicated to caching the video in case streaming does not work. We can share the credentials to this dropbox with everyone who also has youtube access. This solution is free and fast to implement.

**Comment by krrisis** [comment]
Training session in thailand!

**Comment by geleeroyale** [comment]
Here is the guide for streaming/recording and video backup/sharing - feedback welcome. I can also make a video out of this if there is demand, as well as give support in the initial testing period. This text should go to the Wiki.

https://hackmd.io/s/Hyh1MhDgN

**Comment by GriffGreen** [comment]
oh fuck yeah... can I add it to the Wiki... and just remove the keys

**Comment by krrisis** [comment]
thx so much kay!! @GriffGreen there's no key in there I think? 
@joshfairhead can add this to the wiki - close to creating a pull request with some serious updates --> this goes under 'guides' (comms)

**Comment by geleeroyale** [comment]
the key in the post is **my public key** for syncthing!

**Comment by geleeroyale** [comment]
We never added this to the Wiki! Will do so now!

**Comment by geleeroyale** [comment]
Added the info to the Wiki - PR waiting for review: https://github.com/Giveth/giveth-wiki/pull/65

**Comment by krrisis** [comment]
Check, thx kay, added review - prob best if you still do that live obs tutorial for people who are interested. Griff was going to organize bcs he has a gazillion things on his plate but maybe best you kick that off, as Griff, well , has a gazillion things on his plate. :)

**Comment by krrisis** [comment]
on the wiki now

**Comment by geleeroyale** [comment]
I did actually show him around OBS in Barcelona! :)
