### ISSUE TITLE
Optimize the bridge bot between Riot, Slack, Telegram and Rocketchat

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#121]
Things to improve: 

- when sharing urls make sure the markdown is kept (currently lost through the bridge)
- check if it's possible to get account images through the bridge
- check if it's possible to bridge to keybase (don't think it is but needs to be checked)
- .. others will come up

Support & access via @Geleeroyale

**Comment by geleeroyale** [comment]
Hmmm - first off these points concern this software: https://github.com/42wim/matterbridge

We do not use this software to bridge between Slack and Riot. We do use it for single rooms to bridge them to Telegram and to bridge the whole of Aragon from Rocketchat to Riot.

These features that you would like to have are currently not supported it seems. For the markdown it might suffice to make an issue request at the bridge's main repo. User puppeting (avatars ... i.e. bot impersonating other users) is not supported.

For now - keybase is not supported - it may never be supported as it seems keybase goes the security route and does not allow any bots(?) ... the supported protocols are:
*Discord, Gitter, IRC, Mattermost, Matrix, RocketChat, Slack, Steam, Telegram, XMPP*

**However:** It seems like what you really want is more robust bridging of the Aragon community which might be achieved by using the following:
https://github.com/exul/matrix-rocketchat

**Comment by krrisis** [comment]
hey kay, what do we use then between slack & riot and how can we optimize that one?

**Comment by geleeroyale** [comment]
We use our own matrix server, together with this: https://github.com/matrix-org/matrix-appservice-slack

as setup by @perissology 

What do you want to optimize here? The issues you were referring to in the description concern the bridge between rocketchat and matrix

**Comment by krrisis** [comment]
as discussed in comms call further investigate by creating issues where needed or following up:
 
- for riot-slack --> see how we can fix the markdown being lost between slack & riot
- for riot-rocket chat --> idem

If possible log further issues or contact people for riot-rocket to 
- edit/delete messages 
- have avatars come through

thx!

**Comment by geleeroyale** [comment]
The good news is that some of the formatting of markdown works from riot to rocket.

But from there on -  I guess nobody bothered checking - but markdown does not seem to be *fully* supported by neither Slack, nor Rocket-chat. 

Slack can be quoted here: "Since most are not familiar with Markdown, we’ve chosen not to support it." :-/ 

For Rocket.chat I tried to find documentation on message formatting, but I could not find anything. But I tried markdown and it does not work. I.e. the formatting for bold is one star before and after the content, which in markdows means *italic*.

edit/delete messages - like I explained, this is because of the way the transfer protocol works. A bot would need not only the permission to edit or delete messages, this would need a very custom logic from bridge to bridge (and even therein for different room settings), so I am sure this is out of scope for the developers. this might be one of the reasons why "editing" is not a function in matrix and also "delete" will just remove the content, but keep a timestamp of a message that was there.

have avatars come through - We can hope for a point in the future, when this gets some more love:
https://github.com/matrix-org/matrix-appservice-rocketchat
which is the official bridge service. There is one guy working on it his own fork of that, but it does not seem to be usable yet(?) - https://github.com/exul/matrix-rocketchat

---

Bridging will never be perfect and there are some caveats we have to accept, it might take a long time for solutions to appear and fixes to be found. Especially with bridging we should EXPECT for our beloved consistency to break. The best solution in my opinion is to build the community and announce the move on matrix/Riot, as it is easier to go from their system to others 😇 

Nevertheless, I try to reach the developer of matterbridge, but so far without success.

**Comment by geleeroyale** [comment]
I did reach the developer - and hurray(!) - they asked me to open a feature request! So I did open an issue on their GitHub repo: https://github.com/42wim/matterbridge/issues/663

I also attached a (small) Gitcoin bounty that Aragon DAC can fund a little more if you want to incentivice development!

**Comment by geleeroyale** [comment]
fixed in https://github.com/42wim/matterbridge/issues/663
