### ISSUE TITLE
Unicorn Onboarding Onepager

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#72]
Would be great to have a onepager that someone owns and that we keep up-to-date with all the info a new Unicorn should know. (can be on the wiki but let's start in a google doc)

This can link to decisions taken previously ofc (eg #67 ) but needs to be much more than this. 
We also need a role in the roles sheet, someone a new unicorn can turn to for info. 
Such a sheet can also be very useful as a template for future DACs!

Dani proposed to help with this so assigning her for now, also assigning myself for brain-picking :)

**Comment by vojtechsimetka** [comment]
Just putting as a reference something that I have created as onboarding onepager in November last year (there is a gitlab repo as some of the info were private, no longer the case). Most of it is now on wiki and is somewhat up to date, though it is rather difficult to navigate. I would suggest at least making the first section: Important links to be a start.

**Comment by GriffGreen** [comment]
onboarding for unicorns (aka Uniboarding) is being worked on by Lorelei

**Comment by jessicazartler** [comment]
@Danibelle said she was working on Onboarding docs and simplifying the directions in a one-pager and we also discussed ideas for doing video walk throughs -- like "5 Steps to Become a Giveth Unicorn" or "10 Steps ..." as video is much more engaging and people are a bit lazy and prefer to watch video to reading docs :) 

I sent her these examples from my old gig doing software support: (from the archives haha):
https://www.youtube.com/watch?v=bA39Mj4mBEo
https://www.youtube.com/watch?v=JybAc6n-EmA&t=31s
https://www.youtube.com/watch?v=m3WRysHFnYs

We will create an issue for this @Danibelle and work together -- she will do the on cam and I will be here for bouncing ideas and helping with any ideas/content/screen recording apps

**Comment by loietaylor** [comment]
Might be useful for y'all to know the current status: 
- Already there is in depth documentation of the [Unicorn DAC](https://wiki.giveth.io/dac/Unicorn-DAC/) and it's [onboarding process](https://wiki.giveth.io/policy/Unicorn-onboarding/) on the wiki. 
- We have 7 unicorn pledges! (In process of applying to the Unicorn DAC). 
- This is a lot to manage already, ushering them through the onboarding and early operational stages of the DAC. 
- As with most experiments, it's good to keep the controls tight the variables low and the sample size small for the initial phase
- As such, I imagine conditions morphing over the next couple months, and I hope no one puts too much energy into informational material that's just going to become obsolete with changes!
- The Unicorn DAC is for people who are HIGHLY dedicated to Giveth. Being a part of this requires spending so much time on the DApp, the riot, the wiki, the medium, watching all the things going on in the galaxy so that you can appropriately delegate funds to milestones that truly usher us towards the big G Goals. If you aren't able to wade through the documents and take initiative to reach out when you need help, you probably aren't a fit for the Unicorn DAC at this moment. There's value in it not being easy-peasy-lemon-squeezy - it's a filter. 

THAT SAID,,,:
- I LOVE the idea of video tutorials, infographics, easy one pagers, omg they are so great!! And for a long time I've been dreaming of having them for many pieces of Giveth flow. 
- I'm so excited that other people are excited about this!!
- It would be really helpful to have these materials for The Roles Process, The Milestone Making Process, and perhaps: the Milestone reviewing process, the Reward DAO process, creating a DAC or Campaign, etc. And I think all of these are more ready than the Unicorn DAC for this type of material.
The first 3 I mentioned there are ones that I have created at least some of these materials for (some published and some unpublished and back-burner'ed). Get in touch with me, I got resources!

**Comment by krrisis** [comment]
Ok closing this one as the Unicorn DAC onboarding is Loie's domain now and growing on the wiki
