### ISSUE TITLE
One young world - 17-20/10 

### ISSUE THREAD

**Issue by krrisis** [Giveth/Communication#84]
Side event talking side event - lanski will check if he can get a room to talk blockchain for social good
https://www.oneyoungworld.com/summit-2018

**Comment by Pol-Lanski** [comment]
Update: 
1) The Blockchain meetup is going to happen but it's not getting much traction. I am hoping after Akon presenting A-Koin (yes, he will be there...) people will become more acquainted with Blockchain and we will get some traction. Hence the meetup will be after that session.
2) We have gotten a spot in one of the sessions to present during a 3 minutes pitch in front of top shelf media from around the world in what is called "The Spark Show". Nevertheless, since by then we might not have a success story by then, I have suggested to block the slot in the presentation for an Amadeus project too and if we have a success story to tell, I will push Giveth instead in that slot.

**Comment by jessicazartler** [comment]
Please let me know if you need any support on the events side for this --- also have a really cool contact in the Netherlands who is one of the founders of Angel Island and has big VC ties in the EU
https://www.angelisland.co/

He may have some good contacts in the Hague -- good luck with the plans!
